title: Daniel Pinedo
description:
url: "https://pine.do"
author: Daniel Pinedo

show_downloads: false
google_analytics: UA-119529330-1

markdown: kramdown

plugins:
  - jemoji
  - jekyll-seo-tag
  
# Location of the SCSS partials
#
sass:
  sass_dir:   _sass
